development:
  host: localhost
  database: ogcsearch_development

test:
  host: localhost
  database: ogcsearch_test

staging:
  uri: mongodb://heroku_app736601:qjf170a5afe67ccjb85gq2u5n6@dbh29.mongolab.com:27297/heroku_app736601

production:
  uri: mongodb://heroku_app736604:mgeoqql9v827lan0cqm4bsu400@dbh30.mongolab.com:27307/heroku_app736604
